version: '3'
services:
  jenkins-lts:
    image: docker.io/jenkins/jenkins:lts-jdk17
    ports:
      - 8080:8080
      - 50000:50000
  jenkins-2.525-jdk21:
    image: docker.io/jenkins/jenkins:2.534-jdk21
    ports:
      - 8081:8080
      - 50001:50000
