name: CI

on:
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  find-changed-workspaces:
    name: Detect workspace changes
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.find-changed-workspaces.outputs.workspaces }}
      workspaceNodeMatrix: ${{ steps.find-changed-workspaces.outputs.workspace_node_matrix }}
    steps:
      - name: Calculate number of commits in PR
        id: calculate-commits
        env:
          COMMITS: ${{ github.event.pull_request.commits }}
        run: echo "NUMBER_OF_COMMITS=$(($COMMITS + 1))" >> $GITHUB_ENV

      - name: Checkout base branch for diff purposes
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 50 # TODO(awanlin): Temporary fix

      - name: Checkout head branch
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          # Needed for diff
          fetch-depth: ${{ env.NUMBER_OF_COMMITS }}

      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: Find changed workspaces
        id: find-changed-workspaces
        run: node ./scripts/ci/list-workspaces-with-changes.js
        env:
          BASE_REF: origin/${{ github.event.pull_request.base.ref }}

  ci:
    name: Workspace ${{ matrix.workspaceNodeMatrix.workspace }}, CI step for node ${{ matrix.workspaceNodeMatrix.nodeVersion }}
    runs-on: ubuntu-latest
    needs: find-changed-workspaces
    strategy:
      matrix:
        workspaceNodeMatrix: ${{ fromJSON(needs.find-changed-workspaces.outputs.workspaceNodeMatrix) }}
      fail-fast: false
    defaults:
      run:
        working-directory: ./workspaces/${{ matrix.workspaceNodeMatrix.workspace }}

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192
    
    services:
      postgres18:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
      postgres14:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - name: Checkout main branch for tests purposes
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: main
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Node ${{ matrix.workspaceNodeMatrix.nodeVersion }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.workspaceNodeMatrix.nodeVersion }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        run: yarn install --immutable

      - name: check for missing repo fixes
        run: yarn fix --check

      - name: validate config
        if: ${{ hashFiles(format('workspaces/{0}/app-config.yaml', matrix.workspaceNodeMatrix.workspace)) != '' }}
        run: yarn backstage-cli config:check --lax

      - name: type checking and declarations
        run: yarn tsc:full

      - name: prettier
        run: yarn prettier:check

      - name: read knipReports flag from bcp.json
        id: bcpKnipReports
        run: |
          echo "Checking for bcp.json in workspace: workspaces/${{ matrix.workspaceNodeMatrix.workspace }}"
          if [ -f bcp.json ]; then
            echo "Reading knipReports flag..."
            KNIP_REPORTS=$(jq -r '.["knipReports"]' bcp.json)
            echo "knipReports value: $KNIP_REPORTS"
            echo "knip_reports=$KNIP_REPORTS" >> $GITHUB_OUTPUT
          else
            echo "bcp.json not found. Defaulting knip_reports to false."
            echo "knip_reports=false" >> $GITHUB_OUTPUT
          fi

      - name: check knip reports
        if: ${{ steps.bcpKnipReports.outputs.knip_reports == 'true' }}
        run: yarn build:knip-reports --ci

      - name: read listDeprecations flag from bcp.json
        id: bcpListDeprecations
        run: |
          echo "Checking for bcp.json in workspace: workspaces/${{ matrix.workspaceNodeMatrix.workspace }}"
          if [ -f bcp.json ]; then
            echo "Reading listDeprecations flag..."
            LIST_DEPRECATIONS=$(jq -r '.["listDeprecations"]' bcp.json)
            echo "listDeprecations value: $LIST_DEPRECATIONS"
            echo "list_deprecations=$LIST_DEPRECATIONS" >> $GITHUB_OUTPUT
          else
            echo "bcp.json not found. Defaulting list_deprecations to false."
            echo "list_deprecations=false" >> $GITHUB_OUTPUT
          fi

      - name: check list deprecations
        if: ${{ steps.bcpListDeprecations.outputs.list_deprecations == 'true' }}
        run: yarn backstage-cli repo list-deprecations

      - name: check api reports and generate API reference
        run: yarn build:api-reports:only --ci

      - name: build all packages
        run: yarn backstage-cli repo build --all

      - name: lint
        run: yarn backstage-cli repo lint --since origin/main

      - name: publish check
        run: yarn backstage-cli repo fix --check --publish

      - name: test changed packages
        run: yarn test:all --maxWorkers=3
        env:
          BACKSTAGE_TEST_DISABLE_DOCKER: 1
          BACKSTAGE_TEST_DATABASE_POSTGRES18_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres18.ports[5432] }}
          BACKSTAGE_TEST_DATABASE_POSTGRES14_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres14.ports[5432] }}

      - name: read playwrightTests flag from bcp.json
        id: bcpPlaywrightTests
        run: |
          echo "Checking for bcp.json in workspace: workspaces/${{ matrix.workspaceNodeMatrix.workspace }}"
          if [ -f bcp.json ]; then
            echo "Reading playwrightTests flag..."
            PLAYWRIGHT_TESTS=$(jq -r '.["playwrightTests"]' bcp.json)
            echo "playwrightTests value: $PLAYWRIGHT_TESTS"
            echo "playwright_tests=$PLAYWRIGHT_TESTS" >> $GITHUB_OUTPUT
          else
            echo "bcp.json not found. Defaulting list_deprecations to false."
            echo "playwright_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: playwright tests
        if: ${{ steps.bcpPlaywrightTests.outputs.playwright_tests == 'true' }}
        run: |
          yarn playwright install --with-deps chromium chrome
          yarn playwright test

      - name: ensure clean working directory
        run: |
          if files=$(git ls-files --exclude-standard --others --modified) && [[ -z "$files" ]]; then
            exit 0
          else
            echo ""
            echo "Working directory has been modified:"
            echo ""
            git status --short
            echo ""
            exit 1
          fi

  ci-scripts:
    name: Validate scripts/* changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24.x
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - run: yarn test:scripts

  verify:
    name: Workspace ${{ matrix.workspace }}, Verify step
    runs-on: ubuntu-latest
    needs: find-changed-workspaces
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.find-changed-workspaces.outputs.workspaces) }}
      fail-fast: false
    steps:
      - name: Checkout head branch
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22.x
      - name: Install root dependencies
        run: yarn install --immutable
      - name: Verify lockfile duplicates
        run: node scripts/ci/verify-lockfile-duplicates.js workspaces/${{ matrix.workspace }}/yarn.lock
      - name: Verify changesets
        run: node scripts/ci/verify-changesets.js ${{ matrix.workspace }}
  result:
    if: ${{ always() }}
    name: check all required jobs
    runs-on: ubuntu-latest
    needs: [ci, verify]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
